name: 'Module 7 Variables'

run-name: 'Triggered by ${{ github.actor }} on ${{ github.ref_name }}'

on:
    workflow_dispatch: 

env:
    APP_NAME: 'inventory-app' 
    VERSION: '1.0'
jobs:
    build:
        env:
            JAVA_VERSION: '21'
        name: Build Variable Job
        runs-on: ubuntu-22.04
        
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Display APP Name
              run: echo "APP Name is $APP_NAME"

            - name: SHOW VER NAME
              run: echo "APP VERSION is $VERSION"

            - name: Disply Java VER
              run: echo "Java VERSION is $JAVA_VERSION"

            - name: SHOW APP VER AS PER STEP
              run: echo "APP VERSION = $VERSION"
              env:
                VERSION: '2.0'

        
