name: 'Steps Context Demo'
run-name: 'Triggered by ${{ github.actor }} on ${{ github.ref_name }} by event ${{ github.event_name }}'

on:
    workflow_dispatch:
    push:
        branches: 
            - main

jobs:
    build:
        name: 'Build and Tag Application'
        runs-on: ubuntu-22.04
        
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: 'Generate Application Version'
              id: version
              run: |
                SHORT_SHA="${{ github.sha }}::7"
                VERSION="1.0.${ github.run_id }-$SHORT_SHA"

                echo "version=$VERSION" >> "$GITHUB_OUTPUT"
                echo "short_sha=$SHORT_SHA" >> $GITHUB_OUTPUT

                echo "Generated Version: $VERSION"