name: 'Module 7 Variables'

run-name: 'Triggered by ${{ github.actor }} on ${{ github.ref_name }}'

on:
    workflow_dispatch: 

env:
    APP_NAME: 'inventory-app' 

jobs:
    build:
        env:
            VERSION: '1.0'
        name: Build Variable Job
        runs-on: ubuntu-22.04
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Show APP Name
              run: echo "APP Name is $APP_NAME"

            - name: SHOW VER NAME
              run: echo "APP VERSION = $VERSION"

            - name: SHOW APP VER AS PER STEP
              run: echo "APP VERSION = $VERSION"
              env:
                VERSION: '2.0'

        
